language: java
dist: xenial
jdk:
  - openjdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ugurcanlacin_spring-monolith-boilerplate
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - "$HOME/.m2"

addons:
  sonarcloud:
    organization: "faccec8e-66fb-11ea-bc55-0242ac130003"
    token:
      secure: "**************************" # encrypted value of your token
env:
  global:
    secure: CFCQnVtnqKLNTGmQuC5kw2YvhuYos/Zou4OHDLDnMuf/KEBfOinDfGe+ptxfcPEwzCj/d1U2ZLX0i8SW5t3lUfcDqQEd12t0/4oSJN+IH84AbZjafsbZ0oFyFcmvbZl0cukgVtPiZpvzWf6Gdqzm1fgeCx0DEAgl2AmAixntndZSNs9exMGMOp4lY/LzfEJTbcAf2KZU2B7DH5M7PW04jGURWT3uVmIMkkIDllKZo2QC+d+LrPO16OfuwrV9zmTLSjZPc86FYgfaKQ4KBjUzqGtiWX1szS8ooeBcf63Sm8Hjc7/+3C5PfSzMPYplYAuXwTak7lgSfEAVlKzznXsziq7rXgbkOu5gvQoEzEDirXH+MmOZqhUDhwFm+YW08sx36WADn/9SVcJUahtCdy+9OogSHuutR/HQjMNe2/2nCTPpyeUEN6Qebd+wxUJLMaCTNqGSDBl2Kx4N+OE2QnKLa7bubjGwmJVDgu+YUlAFiMf64+4O1z5SBChDgxYiAz+ZATouzEIamVhk1uzToFarCNrKHH/yjeSaoVfPLjKBZTikby3Of5/Uc/Tj4+kfbGs5IESnA1sBWOgDrpoqBxdPh4wBsBe6ndYFo/Yo2gocljdVXrOt9XQsXTSRdqSt7yWjuaQCbW8nKrsiIAnkAuXnIAh1+2ykgJOz57GS+0C5ftk=
