language: java
dist: xenial
jdk:
  - openjdk8

script: 
  - mvn package
  - mvn cobertura:cobertura

script: 

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
cache:
  directories:
  - $HOME/.m2
