language: java
dist: xenial
jdk:
  - openjdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ugurcanlacin_spring-monolith-boilerplate
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - "$HOME/.m2"

addons:
  sonarcloud:
    organization: "faccec8e-66fb-11ea-bc55-0242ac130003"
    token:
      secure: "ce8511jgZwK7v3OXx9952X8bhK4xP86Sa2sFJSHJ/wsGfIx9W9kx4uXEJfZFwLL9rPYKieOOT3bYisNFQtrE4OxbQdGbjh7b/EEl59ZLUsfVIX8AOAscOv5wNaX8uhxHTJAggIdSZKf2N7vEDXLY099kn5QCkUIHGCDJ8y//x9/JYRh/FGmMjxSHJMAgTo6BqHI1d1R2tSE4ZAIEBEMiOVOXPW0209duUjFRzMHnR7I/gIYiv8K2ubSULA0B18gYQ+ajOG9NLq1yxK372QW09QpZ7WEtND7tmxsevr1gyk0yScEIHvNYXbeopCJVj0KanQVPusrlwjkcfUcPcadoftpuzaqyf3Gw3ERJSQRB9ut1T6ey6Q5o0VGhL+ALGWv019xfJhFlI+WDSjGr2vQFe4xqDEnYlxyfo6IIbrlM/xyWQT2yodOzhcF6BlKfRVRaOItUP4L5HNoL5IYlwx8MRYXGhkypWluiaymkB/m+i77qRoVKRJmAVuBP9e9gJoEeYvnvIE8eBEQJQD68UJOg1wownCAMH2cLFDYTeeMxdwCudBvWmUrSzayU2hEIaKAmVXHmq+ZCP8dz0sYGPw9/v67TNADXWmryUVzt8ljWNyzFr3YuFJ49Mzc1jSmWMmKrmiClKFPn/W697V/A6k6jxHlQ0HeTUZ2wIdVHnQ1Xnk4="